apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-demo-deploy
  labels:
    app: ms-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-demo
  template:
    metadata:
      labels:
        app: ms-demo
    spec:
      containers:
        - name: ms-demo
          image: mauron/ms-demo:2             
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080 
          envFrom:
            - configMapRef:
                name: ms-demo-config
            - secretRef:
                name: ms-demo-secret
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          # (Opcional) recursos
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"



