apiVersion: v1
kind: Service
metadata:
  name: ms-demo-2-svc
  labels:
    app: ms-demo-2
spec:
  type: LoadBalancer          # Para acceso interno. Usa NodePort/Ingress si necesitas acceso externo.
  selector:
    app: ms-demo-2
  ports:
    - name: http
      port: 9090           # puerto del Service (equivalente al "host port")
      targetPort: 8080     # puerto del contenedor