name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  continuous-integration:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: sonarqube
      run: |
        mvn clean verify sonar:sonar \
            -Dsonar.projectKey=${{ github.event.repository.name }} \
            -Dsonar.projectName=${{ github.event.repository.name }} \
            -Dsonar.host.url=${{ vars.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Build Docker image
      run: |
        docker build . -t ${{ github.event.repository.name  }}:${{ github.run_number }}
        docker tag ${{ github.event.repository.name }}:${{ github.run_number }} ${{ vars.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.run_number }}

    - name: Push Docker image to Docker Hub
      env:
        DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        docker push ${{ vars.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.run_number }}

  continuous-deployment:

    runs-on: self-hosted

    needs: continuous-integration

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to Kubernetes
      run: |
        cd k8s
        sed -i "s|image: mauron/ms-demo:2|image: ${{ vars.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.run_number }}|g" deployment.yaml
        kubectl apply -f . -n diplomado